spring:
  application:
    name: drawlots-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drawlots?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        
server:
  port: 8080
  servlet:
    context-path: /api
    
# 钉钉配置
dingtalk:
  app-key: your-app-key
  app-secret: your-app-secret
  callback-url: http://your-domain/api/dingtalk/callback

# 飞书配置
feishu:
  app-id: your-app-id
  app-secret: your-app-secret
  callback-url: http://your-domain/api/feishu/callback

# JWT配置
jwt:
  secret: your-jwt-secret-key
  expiration: 86400000 # 一天的有效时间

# IP限制配置
ip:
  record-expiration-days: 30 # IP记录保留30天 